server:
  port: 9009
spring:
  application:
      name: pgw-demo-server-jun-1.0
  datasource:
      url: jdbc:mysql://192.168.165.222:3306/demo?useUnicode=true&characterEncoding=UTF-8
      testWhileIdle: true
      validationQuery: SELECT 1
      username: root
      password: zhangjun666
      driverClassName: com.mysql.jdbc.Driver
      dialect: com.example.demo.config.MySQLDialect


#  jackson:
#1
#测试提交
#    date-format: yyyy-MM-dd HH:mm:ss
  http.converters.preferred-json-mapper: fastjson
#  com.example.demo.data:
#    rest.base-path: /api/pgw/router
mybatis:
  dialect: org.apache.ibatis.dialect.OracleDialect
  #mapper-locations:
    #classpath*: com/example/demo/mapping/*.xml
  #dialect: org.apache.ibatis.dialect.OracleDialect
  #bbase-package: com.example.demo.dao
  #aliases-package: com.example.demo.data
  #underscore-to-camel-case: true